#!/bin/sh
#dropbox service

HOMEDIR=/home/jake
dbuser=jake

DAEMON=.dropbox-dist/dropboxd

start() {
   echo "Starting dropbox..."
   if [ -x $HOMEDIR/$DAEMON ]; then
       HOME="$HOMEDIR"
       start-stop-daemon -b -o -c $dbuser -S -u $dbuser -x $HOMEDIR/$DAEMON
   fi
}

stop() {
   echo "Stopping dropbox..."
   if [ -x $HOMEDIR/$DAEMON ]; then
       start-stop-daemon -o -c $dbuser -K -u $dbuser -x $HOMEDIR/$DAEMON
   fi
}

status() {
   dbpid=grep -u $dbuser dropbox
   if [ -z $dbpid ] ; then
       echo "dropboxd for USER $dbuser: not running."
   else
       echo "dropboxd for USER $dbuser: running (pid $dbpid)"
   fi
}

case "$1" in

   start)
       start
       ;;
   stop)
       stop
       ;;
   restart|reload|force-reload)
       stop
       start
       ;;
   status)
       status
       ;;
   *)
       echo "Usage: /etc/init.d/dropbox {start|stop|reload|force-reload|restart|status}"
       exit 1

esac

exit 0
